### PR TITLE
Ranks

### LINKED ISSUE #77: Ranks updates
**Is your feature request related to a problem? Please describe.**
Ranks are kinda broken, with routes not being visible for admins etc etc. 

**Describe the solution you'd like**
Better handling of ranks.

- [ ] Allow select users (probably admins) to only be ranked manually (so hours don't affect their rank).
- [ ] Certain ranks unachievable (only manual)
*more to come*

### PR DESCRIPTION
**Pull request by Sam-Neale**
Closes #77

### CODE REVIEW

**Review by nic-hanna — APPROVED** [review]
No bugs that I can be bothered writing about and even if I do I'll just get the "not reproducable" comment

**Comment by Sam-Neale** [comment]
In depth reviews please

**Comment by nic-hanna** [comment]
1 per day

**Comment by Sam-Neale** [comment]
Can they stack because there weren't any PRs yesterday IIRC

**Comment by nic-hanna** [comment]
Well yes but there are 4 today, you don’t want it delayed for future days?

**Comment by Sam-Neale** [comment]
Well no I'd quite like to get the 3 (+1 later) done today because tomorrow Ill do the misc stuff and testing before a beta on Boxing Day

**Review by nic-hanna — APPROVED** [review]

**Pull request merged**
