### PR TITLE
New navbar

### PR DESCRIPTION
**Pull request by Sam-Neale**
New NavBar design

#32

### CODE REVIEW

**Comment by Sam-Neale** [comment]
@teddy9264 if you could download this branch and test this that be great

**Review by teddy9264 — CHANGES_REQUESTED** [review]
- Accent Colors do not work
- Changing screen size from mobile to web doesn't work

**Comment by Sam-Neale** [comment]
Accent colour moved to issue #48

**Comment by Sam-Neale** [comment]
Discontinued

**Pull request closed without merging**
