### PR TITLE
Stats

### PR DESCRIPTION
**Pull request by Sam-Neale**
Closing #67 and #66

### CODE REVIEW

**Review by nic-hanna — CHANGES_REQUESTED** [review]
Fix user alignment

Loading continues to load if you have no flights i think

TOO MANY FLAGS?!?!

When in smaller window most common flight is different height to other summaries

**Comment by Sam-Neale** [comment]
> When in smaller window most common flight is different height to other summaries

Unable to reproduce

**Review by nic-hanna — CHANGES_REQUESTED** [review]
After cloning th ebranch then loging in then resert password and logging in then pressing my stats then pressing show all I reieved a rate limiting error "Too many requests"

DENIED

**Comment by nic-hanna** [comment]
Massive gap on the bottom of /stats/va

**Comment by Sam-Neale** [comment]
Is this rate limiting coming from the VACenter API or from the instance? (If its the instance it will be the whole page, if its the API it will be in the console). Are there any other errors?

**Comment by Sam-Neale** [comment]
> Massive gap on the bottom of /stats/va

Ah yes I know what's causing that, from #92

**Comment by nic-hanna** [comment]
The whole page

**Comment by nic-hanna** [comment]
Uneven
image

**Comment by Sam-Neale** [comment]
> pressing show all

Could you clarify what you mean by "View All"

**Comment by Sam-Neale** [comment]
> Uneven
> image

right...

**Comment by nic-hanna** [comment]
> > pressing show all
> 
> Could you clarify what you mean by "Show All"

First blue button on My Sats

**Review by nic-hanna — APPROVED** [review]

**Pull request merged**
